title: Yulin Li's Homepage
page-top-title: Yulin Li
top-section-bg-text: Software Engineering
home-subtitle: Yulin Li&ensp;|&ensp;李昱霖
copyright-text: '&copy; Yulin Li 2023-2024. All Rights Reserved.'
